version: '3.8'

services:
  gateway:
    build: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:3000"
    environment:
      - PORT=${GATEWAY_PORT}
      - FRONT_PORT=${FRONT_PORT}
    depends_on:
      - store-service
      - library-service
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    command: npm run dev

  import-service:
    build: ./import-service
    ports:
      - "${IMPORT_PORT}:3003"
    environment:
      - PORT=${IMPORT_PORT}
    volumes:
      - ./import-service:/app
      - /app/node_modules
    command: npm run dev

  store-service:
    build: ./store-service
    ports:
      - "${STORE_PORT}:3001"
    environment:
      - MONGO_URI=${MONGO_DB_URI}
      - PORT=${STORE_PORT}
    depends_on:
      - mongo-db
    volumes:
      - ./store-service:/app
      - /app/node_modules
    command: npm run dev

  library-service:
    build: ./library-service
    ports:
      - "${LIBRARY_PORT}:3002"
    environment:
      - PORT=${LIBRARY_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=mist_library
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres-db
    volumes:
      - ./library-service:/app
      - /app/node_modules
    command: npm run dev

  front-app:
    build: ./front-app
    ports:
      - "${FRONT_PORT}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./front-app:/app
      - /app/node_modules
    command: npm run dev -- --host

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres-db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgre.sql:/docker-entrypoint-initdb.d/init-postgre.sql

  user-service:
    build: ./user-service
    ports:
      - "${USER_PORT}:3004"
    environment:
      - PORT=${USER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=mist_users
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FRONT_PORT=${FRONT_PORT}
    depends_on:
      - postgres-db
    volumes:
      - ./user-service:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
  postgres-data: